### ISSUE TITLE
Admit Child - Data save failing if model is not valid

### ISSUE THREAD

**Issue by manujshanker** [mrchief/duster.net#2]
If a web user fills incorrect data in any mandatory field on any tab (ex Parent tab) and press submit, if model state is not valid, error is shown next to the field having incorrect data. User is not able to Submit form from the same tab. If user goes to next tab, say Fee and tries to submit, the application does not check for ModelState on other tabs and tries to save it. This submit call fails showing oops! message.

Suggested solution - We can check all the model states of each tab when user clicks on submit button on any tab and disallow the user to save data in case any of the model state is invalid.

**Comment by mrchief** [comment]
@manujshanker I think this was wrongly posted here. I'm open to discussion specific to duster.net but I'll be closing this.
